export const AuthState = {
  SET_KEY: 'SET_KEY',
  SET_USER: 'SET_USER',
  SET_USER_SETUP: 'SET_USER_SETUP',
  SET_TAX: 'SET_TAX',
  CLEAR_USER: 'CLEAR_USER',
};

export const ProductState = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  APPEND_PRODUCTS: 'APPEND_PRODUCTS',
  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
};

export const CustomerState = {
  SET_CUSTOMERS: 'SET_CUSTOMERS',
  APPEND_CUSTOMERS: 'APPEND_CUSTOMERS',
  CLEAR_CUSTOMERS: 'CLEAR_CUSTOMERS',
};

export const CartState = {
  ADD_ITEM: 'ADD_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEMS: 'CLEAR_ITEMS',
};

export const InvoiceState = {
  SET_INVOICE: 'SET_INVOICE',
  APPEND_INVOICE: 'APPEND_INVOICE',
  CLEAR_INVOICE: 'CLEAR_INVOICE',
};
