export const AuthState = {
  SET_KEY: 'SET_KEY',
  SET_USER: 'SET_USER',
  SET_USER_SETUP: 'SET_USER_SETUP',
  CLEAR_USER: 'CLEAR_USER',
};

export const ProductState = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  APPEND_PRODUCTS: 'APPEND_PRODUCTS',
  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
};

export const CustomerState = {
  SET_CUSTOMERS: 'SET_CUSTOMERS',
  APPEND_CUSTOMERS: 'APPEND_CUSTOMERS',
  CLEAR_CUSTOMERS: 'CLEAR_CUSTOMERS',
};

export const CartState = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  UPDATE_CART: 'UPDATE_CART',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  CLEAR_CART: 'CLEAR_CART',
  ADD_QUICKPAY: 'ADD_QUICKPAY',
  REMOVE_QUICKPAY: 'REMOVE_QUICKPAY',
  CLEAR_QUICKPAY: 'CLEAR_QUICKPAY',
};

export const InvoiceState = {
  SET_INVOICE: 'SET_INVOICE',
  APPEND_INVOICE: 'APPEND_INVOICE',
  CLEAR_INVOICE: 'CLEAR_INVOICE',
};
